# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[❯](bold fg:#8fbcbb)"
error_symbol = "[❯](bold fg:#bf616a)"

[directory]
style = "bold fg:#8fbcbb"

[git_branch]
style = "bold fg:#5e81ac"

[git_status]
style = "bold fg:#5e81ac"

[python]
style = "bold fg:#88c0d0"
scan_for_pyfiles = false
format = 'via [python ${version}( \($virtualenv\))]($style) '
