#!/bin/bash
# This script is only intended to run on my home setup, with output names being hardcoded and all.
# Note to self: remember to change this whenever the setup changes.

MONITOR=DP-4
TV=HDMI-0

if xrandr | grep "$TV connected primary"; then
	echo Disabling the TV
	xrandr --output "$TV" --off --output "$MONITOR" --auto --primary
else
	echo Disabling the monitor
	xrandr --output "$MONITOR" --off --output "$TV" --mode 1920x1080 --primary
fi

