#!/bin/bash
# This script is only intended to run on my home setup, with output names being hardcoded and all.
# Note to self: remember to change this whenever the setup changes.

MONITOR=DP-4
TV=HDMI-0

AUDIO_DEFAULT=alsa_output.pci-0000_00_1f.3.analog-stereo
AUDIO_TV=alsa_output.pci-0000_02_00.1.hdmi-stereo

switch_from_to () {
	xrandr --output $2 --auto --primary
	xrandr --output $1 --off
	pactl set-default-sink $3
}

if xrandr | grep "$TV connected primary"; then
	switch_from_to "$TV" "$MONITOR" "$AUDIO_DEFAULT"
else
	switch_from_to "$MONITOR" "$TV" "$AUDIO_TV"
fi

qtile cmd-obj -o root -f restart

